### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [containerd/containerd.io#131]
This issue is being created as part of a CNCF-wide migration effort. For details, see:

- https://github.com/cncf/techdocs/issues/108

Current GA info (before work started on this issue):

- Currently implemented in two ways:
  - Netlify snippet injection
  - Custom partial
- UA IDs:
  - `UA-117325385-1` - CNCF
  - `UA-71407002-1` - owned by ??

### Tasks

- [x] Create a GA4 tag (measurement ID) `G-KGB7V28PEJ`
- [x] [Connect] UA IDs from the GA4 website data stream:
  - [x] `UA-117325385-1`
  - [x] `UA-71407002-1`
- [x] Enable GA4 for **production builds only** via [Netlify snippet injection]
- [x] Confirm that event processing is working:
  - [x] Confirm that the GA4 site tag is receiving events
  - [x] Confirm that the UA site tag, `UA-117325385-1`, is still receiving events
  - [x] ~Confirm that the UA site tag, `UA-71407002-1`, is still receiving events~ Don't have access

### Followup

- #147

[connect]: https://support.google.com/analytics/answer/9973999
[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
All done! 🎉
